
model: DeepFM

data_path: /data/data/train
dataset: movie
field_separator: "	"
seq_separator: " "
USER_ID_FIELD: user
ITEM_ID_FIELD: item
#TIME_FIELD: time
LABEL_FIELD: label
show_progress: false
use_gpu: true

load_col:
    inter: [user, item, label]
    user: [user]
    item: [item, genre]

user_inter_num_interval: "[0,inf)"
item_inter_num_interval: "[0,inf)"

epochs: 3
train_batch_size: 4086
metrics: ["Recall", "NDCG"]
topk: [10]
valid_metric: Recall@10
embedding_size : 2

eval_args:
  group_by: user
  order: RO
  split:
    LS: valid_and_test
  mode: full

train_neg_sample_args: 
    distribution: popularity
    candidate_num: 1
training_neg_sample_num: 1

log_wandb: True
wandb_project: recbole_deepfm
