#environment config
seed : 42
log_wandb: True
wandb_project: diffrec
use_gpu: True

data_path: /data/ephemeral/movie/data/train
#data_path: /data/train
dataset: movie

# dataset config : General Recommendation
USER_ID_FIELD: user
ITEM_ID_FIELD: item
#LABEL_FIELD: label
RATING_FIELD: similarity
#field_separator: ','
field_separator: "	"
seq_separator: " "
load_col: 
    inter: [user, item, similarity] #inter file에서 사용할 cols

rating_threshold: null

# model config
model: DiffRec


noise_schedule: 'linear' #[‘linear’, ‘linear-var’, ‘cosine’, ‘binomial’]
noise_scale: 0.01
noise_max: 0.005
noise_min: 0
time-aware: False



# Training and evaluation config
epochs: 25
train_batch_size: 4096
eval_args:
    group_by: none  #굳이 user로 할 필요가 있나?
    order: RO
    split: #{'RS': [0.8,0.1,0.1]}
        LS: 'valid_and_test'
    mode: full

metrics: ['Recall', 'NDCG', 'Precision']
topk: 10
valid_metric: Recall@10
metric_decimal_place: 4
