#environment config
seed: 42
log_wandb: True
wandb_project: recbole_recvae
use_gpu: true

data_path: /data/data/train
dataset: movie

#dataset config : General Recommendation
USER_ID_FIELD: user
ITEM_ID_FIELD: item

field_separator: "	"
seq_separator: " "
load_col:
    inter: [user, item]

user_inter_num_interval: "[0,inf)"
item_inter_num_interval: "[0,inf)"
train_neg_sample_args: 
    distribution: popularity
    candidate_num: 1

# model config
model: RecVAE

# Training and evaluation config
epochs: 90
train_batch_size: 2048

eval_args:
  group_by: user
  order: RO
  split:
    LS: valid_and_test
  mode: full

metrics: ["Recall", "NDCG"]
topk: [10]
valid_metric: Recall@10














