
model: GRU4Rec
#GRU4Rec, BERT4Rec, SASRec
data_path: /data/data/train
dataset: movie
field_separator: "	"
seq_separator: " "
USER_ID_FIELD: user
ITEM_ID_FIELD: item
TIME_FIELD: time
show_progress: false
use_gpu: true

load_col:
    inter: [user, item, time]
    user: [user]
    #item: [item, genre, director, title, writer, year]
    #item: [item, genre, title]

user_inter_num_interval: "[0,inf)"
item_inter_num_interval: "[0,inf)"

epochs: 20
train_batch_size: 4096
metrics: ["Recall", "NDCG"]
topk: [10]
valid_metric: NDCG@10

eval_args:
  group_by: user
  order: TO
  split: # RS:Random / LS:마지막순서
    LS: valid_and_test #각 그룹의 마지막 두 데이터를 Valid와 Test에 사용
  mode: full

# train_neg_sample_args: None
neg_sampling : Null

log_wandb: True
wandb_project: recbole_seq
    #user: [user, type]
    #item: [item, genre, director, title, writer, year, year_bin, popularity_bin]